### PR TITLE
Deleting threads from users

### LINKED ISSUE #1156: Add option to delete all threads and replies by a user
Add an option in the admin panel underneath users to delete all threads from a user. This is useful to delete threads in bulk while also banning them after they post spam en masse.

### PR DESCRIPTION
**Pull request by franbarbalopez**
Hi, im glad to contribute in this project for the first time :) !

This PR Resolves #1156 

As an admin you can now delete all the threads from an user with a new option on the users table.

image

As an admin or moderator you can now delete all threads from user when banning them just checking **delete threads** on the modal.

image

### CODE REVIEW

**Comment by ProjektGopher** [comment]
> [!TIP]
> By including the string `Resolves #1156` in your PR body, you can link the issue directly so that it's closed if this PR is merged.

**Comment by driesvints** [comment]
Thanks a bunch for this one @franbarbalopez!

**Comment by tvbeek** [comment]
@franbarbalopez Thanks, I just used it for the first time, and it works good and save me a lot of clicks.

**Comment by franbarbalopez** [comment]
@driesvints @tvbeek Thank you both for your words! The project was easy to setup and work with, really good work <3

**Pull request merged**
