### PR TITLE
Done : Move descriptions below create thread views

### PR DESCRIPTION
**Pull request by ShaungBhone**

### CODE REVIEW

**Comment by driesvints** [comment]
Hey @ShaungBhone, thanks for this! Can you provide a screenshot how it looks now?

**Comment by ShaungBhone** [comment]
here
image

**Comment by driesvints** [comment]
I think we still need to update the edit form?

**Comment by ShaungBhone** [comment]
Yeah. I'm worried that you don't like my design. If you like this design, I'll make new PR for edit thread.

**Comment by driesvints** [comment]
I like it. Please also update the edit form in this PR 👍

**Comment by driesvints** [comment]
Thanks!

**Pull request merged**
