### PR TITLE
update alpinejs to v3

### LINKED ISSUE #718: Update Alpine to v3

### PR DESCRIPTION
**Pull request by faissaloux**
resolves #718

### CODE REVIEW

**Comment by driesvints** [comment]
Are you sure there's no code changes needed? https://alpinejs.dev/upgrade-guide

**Comment by faissaloux** [comment]
> Are you sure there's no code changes needed? https://alpinejs.dev/upgrade-guide

Oops! You right .. I'll work on it

**Comment by faissaloux** [comment]
I made changes for alpine v3 and everything work fine, except this weird problem with Article tag filter and pagination (Forum tag filter/pagination works fine)

- After selecting a tag the filter applies but the modal open again and won't close.
- After clicking on a page in pagination bar weirdly opens the filter modal.

I really don't know what's the problem here, so if anyone knows why this happens HELP!

https://user-images.githubusercontent.com/60013703/141702649-4a40b665-d2d2-4cd4-91d1-b45de8a8f1a1.mp4

**Comment by joedixon** [comment]
I have pulled this down and am experiencing the same issue. I'll try and take a look later today.

Out of interest, I notice you have used `$nextTick` in a lot of places. Were you noticing issues without it?

**Comment by faissaloux** [comment]
> I have pulled this down and am experiencing the same issue. I'll try and take a look later today.
> 
> Out of interest, I notice you have used `$nextTick` in a lot of places. Were you noticing issues without it?

Yes I had issues without $nextTick. In Alpinejs V3 ```x-init``` no longer accepts a callback return so I have to use $nextTick.

https://alpinejs.dev/upgrade-guide#x-init-no-callback

**Comment by joedixon** [comment]
> Yes I had issues without $nextTick. In Alpinejs V3 `x-init` no longer accepts a callback return so I have to use $nextTick.
> 
> https://alpinejs.dev/upgrade-guide#x-init-no-callback

Thanks, I found the same issues.

Just to give you a general update. The modal issue you were experiencing seems to be related to Livewire. If I remove `wire:click` then it works as expected.

We're actually going to remove Livewire from that page and bring it more inline with the forum overview. Once I have done this, I'll rebase this PR and see what (if anything) is still not working as expected.

Thank you for your hard work on this. I will need some of the Alpine v3 functionality for the mentions PR I'm working on.

**Comment by faissaloux** [comment]
> "We're actually going to remove Livewire from that page and bring it more inline with the forum overview"

This exact idea I had when I faced this problem because it appears only with Livewire.

**Comment by joedixon** [comment]
@faissaloux thank you for your work on this. I'm closing this PR, but your hard work is included on https://github.com/laravelio/laravel.io/pull/764

**Pull request closed without merging**
