### PR TITLE
Add a .well-known/security.txt

### PR DESCRIPTION
**Pull request by tvbeek**
This is a follow up for #776 

See: https://securitytxt.org/ for more information about this file

I only add the email and not the wanted expires because I didn't know how long you want to have this. (And it means this need to be updated once in a while)

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks @tvbeek. Can you also link to the security policy? https://github.com/laravelio/laravel.io/security/policy

**Comment by tvbeek** [comment]
@driesvints yes, it is added.

**Comment by driesvints** [comment]
Thanks @tvbeek 

If you're willing, can you also send this to the repo of the pastebin?

**Comment by tvbeek** [comment]
> Thanks @tvbeek
> 
> If you're willing, can you also send this to the repo of the pastebin?

Sure, done in https://github.com/laravelio/paste.laravel.io/pull/91

**Pull request merged**
