### PR TITLE
#587:Add database schema dump for faster migration

### LINKED ISSUE #587: Add databse dump to use laravel latest feature.
I noticed huge speed improvements on running migrations when I switched from tradition migration to schema dumps.
It will be great to add support for schema dumps.

### PR DESCRIPTION
**Pull request by pushpak1300**
This PR resolves #587.

### CODE REVIEW

**Comment by pushpak1300** [comment]
@joedixon and @driesvints Let me know your thoughts on this.

**Comment by driesvints** [comment]
Hey @pushpak1300, we're using an in-memory database to run the tests so this won't have any effect: https://github.com/laravelio/laravel.io/blob/main/phpunit.xml#L22-L23

It's best that you make use of Parallel testing which I added recently: `php artisan test --parallel`

**Comment by pushpak1300** [comment]
Yes @driesvints I know that I was talking about normal migration while developing.

**Comment by driesvints** [comment]
Ah I see. I'll re-open this and have a look soon.

**Comment by driesvints** [comment]
Thanks for this. I pushed this myself to main. Indeed refreshes much faster 👍

**Pull request closed without merging**
