### PR TITLE
Add hover state to thread replies link

### PR DESCRIPTION
**Pull request by faissaloux**
#820 follow up

image

### CODE REVIEW

**Comment by driesvints** [comment]
Heya, I don't think we use underline anywhere else. Can you just add the same hover color we use on all other links?

**Comment by faissaloux** [comment]
> Heya, I don't think we use underline anywhere else. Can you just add the same hover color we use on all other links?

Actually we do use underline everywhere the difference I made here is the color. ( Other links just underline without changing color ). Should I do the same here ( Underline without changing color ) !

**Comment by driesvints** [comment]
Ah right, sorry!

**Comment by driesvints** [comment]
Thanks!

**Pull request merged**
