### PR TITLE
Add user ban reason

### PR DESCRIPTION
**Pull request by orkuncoding**
This PR #874 . I add a textarea to write user ban reason in user ban modal. Only admin can see users ban reasons.

### CODE REVIEW

**Review by driesvints — CHANGES_REQUESTED** [review]
Heya, thanks for your PR! Can you do these changes and make sure StyleCI and tests are passing?

**Comment by driesvints** [comment]
@orkuncoding it seems you applied my changes but the other references need updating as well.

**Comment by orkuncoding** [comment]
> @orkuncoding it seems you applied my changes but the other references need updating as well.

I am sorry. I know but I did not have enough time to check and fix this. I will fix before weekend.

**Comment by driesvints** [comment]
@orkuncoding did you find time already for this?

**Comment by orkuncoding** [comment]
I had to change my computer. I checked everything and all test passed but I don't know why it got worse. It needs a little bit more work on it.

**Comment by orkuncoding** [comment]
I must fix many things because of windows so i will close this and try again next week.

**Pull request closed without merging**
