### PR TITLE
Show usernames when hovering over like icon

### LINKED ISSUE #990: Show usernames when hovering over like icon
When hovering on a like icon, when it has likes, show the usernames who liked a post. This can just be a `title` attribute and limited to ~10 with "and x more" in a similar fashion as the GitHub hover behaviour:

Screenshot 2024-01-03 at 15 23 47

### PR DESCRIPTION
**Pull request by faissaloux**
Resolve #990 

## Article Page
Screenshot from 2024-01-04 15-04-05

Screenshot from 2024-01-04 15-04-51

### More than 10 likes

Screenshot from 2024-01-04 15-06-08

## Articles Overview
Screenshot from 2024-01-04 03-19-38

## Threads Overview
Screenshot from 2024-01-04 13-58-45

## Thread Page
Screenshot from 2024-01-04 14-07-27

## Thread Reply
Screenshot from 2024-01-04 15-07-18

## User Articles
Screenshot from 2024-01-04 14-44-03

## User threads
Screenshot from 2024-01-04 14-41-23

## User replies
Screenshot from 2024-01-04 14-28-05

### CODE REVIEW

**Comment by driesvints** [comment]
Very cool @faissaloux! Did you mean to send this in as a draft?

**Comment by faissaloux** [comment]
Yes still in progress, I'll turn it ready whenever it is.

**Comment by driesvints** [comment]
Thanks a bunch @faissaloux!

**Comment by faissaloux** [comment]
Happy to help!

**Pull request merged**
