### PR TITLE
Adds icons to navigation dropdown

### LINKED ISSUE #952: Add icons before menu items in dropdown
Add some icons before the menu items in the dropdown menu.

Screenshot 2023-07-27 at 14 30 08

### PR DESCRIPTION
**Pull request by ProjektGopher**
Resolves #952 
Screenshot 2023-07-27 at 9 42 20 AM

### CODE REVIEW

**Comment by driesvints** [comment]
Very cool! Thanks @ProjektGopher 

I'm just wondering if we could vertical align the icons and text a little better? I think that can be done with flexbox on each anchor tag but 100% sure.

**Comment by joedixon** [comment]
Thanks @ProjektGopher! As @driesvints mentioned, you should be able to vertically align the icons and text with the follwing (though not sure if removing the `inline-block` may cause a different issue):

```diff
- <a href="{{ route('profile') }}" class="inline-block w-full lg:px-4 lg:py-3">
+ <a href="{{ route('profile') }}" class="flex items-center w-full lg:px-4 lg:py-3">
    <x-heroicon-o-user class="w-4 h-4 inline mr-1" />
    Your Profile
</a>
```

**Comment by ProjektGopher** [comment]
No worries. I can do that in about an hour. I hadn't even noticed until you pointed it out, haha. I was kind of rushing when I did it as a way to get some momentum going for the day. 🤣

**Comment by ProjektGopher** [comment]
@driesvints @joedixon I had five mins before taking my daughter to daycare - here it is

Screenshot 2023-07-28 at 10 01 14 AM

**Comment by driesvints** [comment]
Perfect thanks! I changed the admin one to a shield instead.

**Pull request merged**
