### PR TITLE
Implement Laravel email verification  (#421)

### PR DESCRIPTION
**Pull request by pushpak1300**
@joedixon   I'm having a problem while running the test case.
All session-related test case is not working.
Any Issue?

### CODE REVIEW

**Comment by pushpak1300** [comment]
Yes @joedixon .
Only session related test are not working.
I don't understand the issue.😭

**Comment by pushpak1300** [comment]
@joedixon You can check!

**Comment by pushpak1300** [comment]
can you review @driesvints ?

**Comment by driesvints** [comment]
I've opened a new PR for this (with your commits) which fixes some things, cleans up the old code and implements a few other things like verification after an email address got changed: https://github.com/laravelio/laravel.io/pull/559

Thanks for your work @pushpak1300

**Comment by pushpak1300** [comment]
Thanks @driesvints

**Pull request closed without merging**
