### PR TITLE
create: security.md

### PR DESCRIPTION
**Pull request by HDVinnie**

### CODE REVIEW

**Comment by HDVinnie** [comment]
Note: I have tried emailing the provided email in the README and it seems its not valid anymore.

```
<security@laravel.io>: host mx2.improvmx.com[13.36.222.39] said: 550 5.1.1 The
    email account that you tried to reach does not exist. Please try
    double-checking the recipient's email address for typos or unnecessary
    spaces.
    ```

**Comment by tvbeek** [comment]
I think as an addition this information could be placed in `.well-known/security.txt`

see: https://securitytxt.org/

**Comment by driesvints** [comment]
Thanks @HDVinnie

**Comment by driesvints** [comment]
@tvbeek good idea. Can you send in a PR for that?

**Pull request merged**
