### PR TITLE
Lock forum threads

### LINKED ISSUE #697: Lock a forum thread
Sometimes you want to lock a thread from receiving more comments. For example, the below post was made in a non-english language while we only allow English as our main language. Ideally we can lock the thread and leave a comment to urge them to submit a new one. This way they don't lose the content. 

Locked threads shouldn't show up in the forum overview, search results, user profiles, ...

Admins and moderators can still reply to locked threads. 

A locked thread receives a lock symbol after its title and a "locked by username" message below it.

https://laravel.io/forum/buenas-tarde-me-podrian-ayudar-con-una-relacion-de-3-tablas

### PR DESCRIPTION
**Pull request by faissaloux**
This PR adds ability to lock forum thread.

resolve #697

### CODE REVIEW

**Comment by faissaloux** [comment]
# Unlocked thread [Admin/Moderator]
Screenshot from 2021-10-13 11-40-10

# Locked thread (By clicking on the lock)
Screenshot from 2021-10-13 11-47-04

Admin/Moderator can unlock the thread by clicking on the lock again

## User can't comment on locked thread
Screenshot from 2021-10-13 11-49-11

**Comment by driesvints** [comment]
@faissaloux can you rebase with main? That should fix the StyleCI issues.

**Comment by driesvints** [comment]
@faissaloux heya, I'm so sorry I didn't get to this yet. Could you maybe rebase this PR with master and make sure it's adapted for Tailwind v3? I'll try to work on it in the next couple of weeks. Thanks!

**Comment by faissaloux** [comment]
@driesvints done 🚀

**Comment by driesvints** [comment]
Thanks for this @faissaloux! Sorry it took me so long to get to this.

**Pull request merged**
