### PR TITLE
Implement thread detail page

### LINKED ISSUE #650: Add hyperlinks around avatars
Both the community section and moderators section as well as users on the forum overview don't have hyperlinks around their avatars.

### PR DESCRIPTION
**Pull request by joedixon**
Also resolves #650 

Waiting on designs for action buttons (edit, subscribe, delete, etc) before implementation is complete.

Screenshot 2021-07-16 at 13 32 32

### CODE REVIEW

**Comment by driesvints** [comment]
Might also be cool to add something that shows who selected an answer?

Like: https://github.com/laravel/framework/discussions/18735#discussioncomment-31239

Screen Shot 2021-07-18 at 15 14 02

**Comment by joedixon** [comment]
> Might also be cool to add something that shows who selected an answer?
> 
> Like: [laravel/framework#18735 (comment)](https://github.com/laravel/framework/discussions/18735#discussioncomment-31239)
> 
> Screen Shot 2021-07-18 at 15 14 02

Love this idea, but can we add this later on as we don't currently track who marks a solution as correct?

**Comment by joedixon** [comment]
Screenshot 2021-07-30 at 16 31 53

Screenshot 2021-07-30 at 16 31 13

Screenshot 2021-07-30 at 16 10 20

https://user-images.githubusercontent.com/3438564/127677391-40443b1f-ceea-43d1-97b8-1df12ca98e29.mov

**Review by driesvints — CHANGES_REQUESTED** [review]
Just the few minor changes I highlighted in our Telegram convo.

**Pull request merged**
