### PR TITLE
switch to relative dates

### LINKED ISSUE #753: Switch to relative dates for threads and replies
It's better that we switch to a relative "x time ago" format for datetime indication on threads and replies because people live in timezones and will maybe sometimes be confused because of the way things work currently. GitHub Discussions also uses a relative time format.

Apply this everywhere: thread detail, forum overview, user profile.

Articles should remain as is with the exact date.

### PR DESCRIPTION
**Pull request by faissaloux**
resolves #753

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks!

**Comment by driesvints** [comment]
Can you also post a screenshot of a thread?

**Comment by faissaloux** [comment]
> Can you also post a screenshot of a thread?

Screenshot from 2021-11-18 14-04-05

Screenshot from 2021-11-18 14-05-57

**Comment by driesvints** [comment]
Hmm for some reason those dates don't seem properly aligned with the username?

**Comment by driesvints** [comment]
Which browser is that?

**Comment by faissaloux** [comment]
> Which browser is that?

Firefox

**Comment by faissaloux** [comment]
> Hmm for some reason those dates don't seem properly aligned with the username?

I'll check that

**Comment by driesvints** [comment]
Weird. It aligns properly for me in Firefox on macOS

**Comment by joedixon** [comment]
> I'll check that

I think you can just add an `items-center` to the flex container?

**Comment by faissaloux** [comment]
@driesvints I'm using Linux!!
@joedixon I have tried flex thing but didn't work, I found that the problem is the font I fixed it using negative margin bottom

Screenshot from 2021-11-18 14-46-18
 
What do you think!

**Comment by driesvints** [comment]
Think we'll just leave it as is if it's only on Linux.

**Comment by driesvints** [comment]
Thanks!

**Comment by faissaloux** [comment]
> Think we'll just leave it as is if it's only on Linux.

I think yes, if it's working on other systems the margin will ruin it

**Pull request merged**
