### PR TITLE
Upgrade to Vite5

### LINKED ISSUE #989: Upgrade to Vite v5 and Laravel vite-plugin v1

### PR DESCRIPTION
**Pull request by faissaloux**
Resolves #989

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks!

**Comment by driesvints** [comment]
Had to revert this one. Broke things on production:

Screenshot 2024-01-06 at 11 11 22

**Comment by faissaloux** [comment]
That's weird!

**Comment by driesvints** [comment]
@faissaloux managed to merge https://github.com/laravelio/laravel.io/pull/1024 which fixes this

**Pull request merged**
