### PR TITLE
Fix nav links

### PR DESCRIPTION
**Pull request by faissaloux**
This PR fix nav links that was limited only on link text and not the whole tab

# Before
before1
before2

# After
after1
after2

### CODE REVIEW

**Comment by driesvints** [comment]
Hmm I don't really see any issue here sorry

**Comment by faissaloux** [comment]
You can't click on the tab to go to the link, you have to click exactly on text!!

**Comment by driesvints** [comment]
Ah now I see it. Thanks, I'll check into this later.

**Review by joedixon — APPROVED** [review]
Great addtion @faissaloux, thank you!

**Comment by faissaloux** [comment]
Happy to help 😄

**Pull request merged**
