### PR TITLE
Migration to Unsplash API

### LINKED ISSUE #1085: Migrate to Unsplash API
Unsplash decided to sunset their https://source.unsplash.com domain without any warning so now all image fetching is broken. We'll have to migrate to their API but think that'll get us into API limits. I don't know if the generated urls from Unsplash are long lived. If they are we could maybe save them in the database otherwise we might have to run a scheduled job to refresh them during their TTL.

### PR DESCRIPTION
**Pull request by tauseefsshah**
This PR fixes #1085 
Adding the tests to this PR then it will be gtg

### CODE REVIEW

**Comment by tauseefsshah** [comment]
Hi @driesvints 

Please review this PR and lmk if the approach looks good. In the meantime I'll add the tests.

**Comment by driesvints** [comment]
Hi @tauseefsshah. This looks really good! Thank you so much for working on this.

It seems we'll need to do a couple of more steps before we're production ready. Would it be possible to place the following below every photo on the article itself (not on the preview photos on the homepage). This can be an `xs-text`.

> Photo by [Annie Spratt](https://unsplash.com/@anniespratt?utm_source=your_app_name&utm_medium=referral) on [Unsplash](https://unsplash.com/?utm_source=your_app_name&utm_medium=referral)

We should also save the author name and link to their unsplash profile in the database.

**Comment by driesvints** [comment]
Screenshot 2024-10-02 at 08 30 51

**Comment by tauseefsshah** [comment]
Hi @driesvints Thank you and you're welcome!

Sure I will add the text with the links.

One quick query, should I just create a json column for this which will store the `image_url`, `author_name` and `author_profile_url` or store the data in separate columns?

**Comment by driesvints** [comment]
Storing in separate columns is fine 👍

**Comment by tauseefsshah** [comment]
Hi @driesvints, Have added the attributes below the image. 

image

**Comment by tauseefsshah** [comment]
This PR introduces the following changes in the db:

- Renames the column `hero_image` to `hero_image_id` for better verbosity
- Add columns `hero_image_url`, `hero_image_author_name` and `hero_image_author_url`

**Comment by driesvints** [comment]
Still waiting on Unsplash btw. Will get back here once I have something to share.

**Comment by tauseefsshah** [comment]
Thanks for sharing the updates
It takes this long for production access 🤯

**Comment by driesvints** [comment]
Finally gotten production access. Thanks a bunch for this one!

**Pull request merged**
