### PR TITLE
Add feature - Optional email/notification message when deleting a post

### LINKED ISSUE #696: Optional email/notification message when deleting a forum post
When deleting a post I'd like to add an optional message that's emailed to the user. For example, the below post was made in a non-english language while we only allow English as our main language. Ideally we can inform them why their thread was removed.

By default, a message can be pre-filled that says the post was in violation of our forum rules (with a link to the rules).

https://laravel.io/forum/buenas-tarde-me-podrian-ayudar-con-una-relacion-de-3-tablas

### PR DESCRIPTION
**Pull request by Gbemiro8**
resolves #696 

Allows admin/moderator to give a reason why article is deleted to the author.

feature (1)

mail_feature
notification_feature

### CODE REVIEW

**Comment by driesvints** [comment]
Wow, thanks for this @Gbemiro8! I'm not sure when I'll have time to review this but appreciate you pushing this! Thanks! 🙂 

Will try to review as soon as I'm able.

**Comment by driesvints** [comment]
Sorry, still haven't gotten to this yet. Hope so to do that rather sooner than later.

**Comment by Gbemiro8** [comment]
Hope so too :)

**Comment by driesvints** [comment]
Hey @Gbemiro8, I'm sorry I didn't see this earlier. I finally had some time to dig into this but it seems you built this feature for articles while it was meant for forum threads (see the link I posted in the original issue). We'll have to convert this to forum threads. At this time, this isn't needed for articles because that works with an approval system.

**Comment by driesvints** [comment]
I'm unfortunately going to have to close this one as it's mis-implemented. Really appreciate the work here but we need to have the right implementation before we can move forward with this.

**Comment by Gbemiro8** [comment]
That's fine, I'll do the right implementation soon enough if still needed or maybe just check out other issues :)

**Pull request closed without merging**
