### PR TITLE
moved the github and twitter icon out of community and to nav bar

### LINKED ISSUE #962: Move social icons
Move the GitHub and Twitter icon links out of the "community" dropdown and left of the search icons on the top bar.

Screenshot 2023-11-02 at 10 33 33

### PR DESCRIPTION
**Pull request by BibinVJ**
fixes #962 

Moved the social icons out of the community dropdown and added them near the search icon, refer screenshot.

##Steps to reproduce
- open the home page and notice the navigation bar.

### CODE REVIEW

**Comment by driesvints** [comment]
Nice. Could you show a screenshot?

**Comment by BibinVJ** [comment]
sorry forgot to add it

icon-change-laravel

**Comment by driesvints** [comment]
Thanks!

**Comment by BibinVJ** [comment]
anytime : )

**Pull request merged**
