### PR TITLE
#579 : Added Tip to set Twitter Handle

### PR DESCRIPTION
**Pull request by pushpak1300**
This PR adds resolves the issue for #579 

**Screenshot of the added tip:**
Screenshot from 2021-01-31 17-34-45

### CODE REVIEW

**Comment by pushpak1300** [comment]
@joedixon can you review it?

**Comment by driesvints** [comment]
@pushpak1300 yes. Please have a little patience as Joe and I are also working day time jobs. We'll get to this when we have time.

**Comment by pushpak1300** [comment]
yea @driesvints.

**Comment by driesvints** [comment]
Thanks! :)

**Pull request merged**
