### PR TITLE
Add a new default avatar using a greyscale Laravel logo

### LINKED ISSUE #688: New default avatar
Figure our a way to show a grayed out Laravel logo as a default avatar instead of the current default GitHub one.

### PR DESCRIPTION
**Pull request by joelbutcher**
Resolves #688

Screenshot 2021-11-19 at 15 11 27

Screenshot 2021-11-19 at 14 44 58

Screenshot 2021-11-19 at 14 45 01

Screenshot 2021-11-19 at 14 47 14

Screenshot 2021-11-19 at 15 11 00

Screenshot 2021-11-19 at 15 11 04

### CODE REVIEW

**Comment by driesvints** [comment]
Can you post some screenshots of the profile page, thread detail page, forum overview page and homepage with the user cloud so we can see how this looks?

**Comment by joelbutcher** [comment]
@driesvints Yup, I took screenshots, but in my haste forgot to upload them with the PR 🤦

**Comment by driesvints** [comment]
@joelbutcher hmm I'm now thinking that maybe the Laravel.io logo might be a bit better. Can you replace that with https://github.com/laravelio/laravel.io/blob/main/public/images/laravelio-icon.svg ? It can even be a slightly more lighter gray so it blends in with the background a bit more. The profile image setting one can be a bit smaller like the one on the profile page.

**Comment by joelbutcher** [comment]
@driesvints like this?


Screenshot 2021-11-22 at 09 34 28

Screenshot 2021-11-22 at 09 41 28

Screenshot 2021-11-22 at 09 41 24

Screenshot 2021-11-22 at 09 34 25

**Comment by joelbutcher** [comment]
@driesvints how do these screenshots look to you?

**Comment by driesvints** [comment]
@joelbutcher I haven't found time yet to look at this yet, sorry. Might be a while.

**Comment by driesvints** [comment]
@joelbutcher heya, I'm so sorry I didn't get to this yet. Could you maybe rebase this PR with master and make sure it's adapted for Tailwind v3? I'll try to work on it in the next couple of weeks. Thanks!

**Comment by joelbutcher** [comment]
@driesvints done 👍

**Comment by driesvints** [comment]
Thanks for this @joelbutcher! Sorry it took this long before I got to this.

**Comment by joelbutcher** [comment]
@driesvints No problems - I just assumed you're busy with the next Laravel release this month!

**Pull request merged**
