### PR TITLE
Reskin forum overview page

### LINKED ISSUE #501: Filter Forum posts
Hello,

While looking at the forum I sometimes miss a option to filter the posts by the following criteria:

- Answered/Not Answered/With comments/Without comments
- Date

Great work, see you :)

### LINKED ISSUE #518: Make "tags" filter collapsible on mobile
I've attached a screenshot. On an iPhone XR, the tags list takes up the entire viewport. I think it should be collapsible or collapse by default on mobile devices. 
60D448BF-CD98-4F17-ADB3-89DC5171FEFD

### PR DESCRIPTION
**Pull request by joedixon**
Resolves #501 
Resolves #518

Screenshot 2021-02-12 at 13 21 15

Screenshot 2021-02-12 at 13 22 05

### CODE REVIEW

**Review by driesvints — CHANGES_REQUESTED** [review]
Your buttons don't need a "tag" attribute. Just determine that based on passing a href or not.

We'll need to implement a way to retrieve the top three solution providers to populate the community section.

**Comment by driesvints** [comment]
@paras-malhotra is there a way to prevent the bot from commenting when all checks pass? I think it's only of interest when something's amis. And even then I feel like the GitHub status says the same? Not sure how the bot provides benefit here?

**Comment by paras-malhotra** [comment]
Sure @driesvints, appreciate the feedback. We modeled it after other bots like Sonarcloud and Coveralls that comment even if everything's 100%, just as an indication that all's well. I do see the value in commenting only if the analysis failed.

We'll be working on a preferences section on the website soon, that will allow folks to change the bot behaviour.

**Comment by driesvints** [comment]
@paras-malhotra thanks! Yeah just trying to be honest in my feedback :)

**Comment by paras-malhotra** [comment]
Absolutely @driesvints, much appreciated! ❤️ We would love to hear more from you as you go along and experience the product! It would help us a lot!

**Comment by paras-malhotra** [comment]
@driesvints, we've now implemented the feature to control bot comments! You can login to Enlightn and go to your project settings to change bot comment behaviour. There are 4 options:

1. Comments disabled.
2. Comment when new issues are introduced.
3. Comment when any issues exist (whether new or not).
4. Always comment.

**Comment by driesvints** [comment]
@paras-malhotra awesome! Thanks a bunch. I've set it to 2. for now.

**Comment by driesvints** [comment]
@paras-malhotra awesome, thanks!

**Pull request merged**
