### PR TITLE
added feature to make pagination configurable and fixed #612

### LINKED ISSUE #612: Pagination on last forum page is off
Screenshot 2021-03-11 at 11 21 25

### PR DESCRIPTION
**Pull request by bhushan**
- In most of the places we are using pagination count as 20, made it configurable so we can change it whenever needed.
- added pagination layout fix on threads page.

Screenshot 2021-04-17 at 5 15 48 AM

### CODE REVIEW

**Comment by bhushan** [comment]
original

Screenshot 2021-04-17 at 5 29 29 AM


- added flex-col and gap-6 to make it look nicer on big pagination

Screenshot 2021-04-17 at 5 27 20 AM

- after setting PAGINATION_ON_EACH_SIDE_COUNT=1

Screenshot 2021-04-17 at 5 27 37 AM

**Comment by bhushan** [comment]
fixes #612

**Comment by driesvints** [comment]
Atm we're not looking into making the pagination configurable, sorry. The `onEachSide` is probably a good idea. Can you send in a PR with just those changes? Thanks.

**Comment by bhushan** [comment]
Hi,  check @driesvints #624

**Pull request closed without merging**
