### PR TITLE
Implement article detail page

### PR DESCRIPTION
**Pull request by joedixon**
I have one concern with this PR and that is the headings over the images. As per the designs, the text is white or light grey and so if we select the wrong image or the wrong section of the image is displayed on mobile, it won't be readable. It may be possible to get around this by simply being sensible with our hero image choices, but I thought it was worth raising.

Screenshot 2021-08-13 at 21 50 52

Screenshot 2021-08-13 at 21 52 24

Screenshot 2021-08-13 at 21 51 11

### CODE REVIEW

**Comment by driesvints** [comment]
Can we have a permanent transparent black overlay on top of the image? Not sure if that's possible? Something to "dim" it so the white on top for the tags and text is never an issue?

**Comment by tvbeek** [comment]
Maybe it is possible to have a tin (1px) dark border around the text, it's a technique that I have used on big screens to make it readable. But I'm not sure how it will point out in the design and how it will work out with the smaller text.

**Comment by joedixon** [comment]
Thanks for the suggestions 🙌  I tried out some things.

**Text outline**
I thought I was going to like this idea, but it won't work on the smaller text. Have you had any success with that before @tvbeek?

Screenshot 2021-08-16 at 17 01 40

**Darken the background**
I think works nicely, I've applied a 20% linear gradient. See before and after below for both a light image and a dark image.

Screenshot 2021-08-16 at 17 03 39 

Screenshot 2021-08-16 at 17 03 46

Screenshot 2021-08-16 at 16 57 51

Screenshot 2021-08-16 at 17 00 59

**Comment by driesvints** [comment]
@joedixon looks good. But I'd make the "time to read" also white. Currently bit hard to read on both fixed versions.

**Comment by joedixon** [comment]
Will get on to that later today or tomorrow 👍

**Comment by joedixon** [comment]
Great, I think it's ready for a review when you are @driesvints

**Comment by driesvints** [comment]
I spot one more thing. On all articles the name of the author isn't aligned to the left:

Screen Shot 2021-08-16 at 21 00 59

**Comment by joedixon** [comment]
> I spot one more thing. On all articles the name of the author isn't aligned to the left:

Great spot! I hadn't noticed as my bio and name are about the same length 😂

**Comment by driesvints** [comment]
Great job @joedixon

**Comment by tvbeek** [comment]
> 
> **Text outline**
> I thought I was going to like this idea, but it won't work on the smaller text. Have you had any success with that before @tvbeek?
> 
> **Darken the background**
> I think works nicely, I've applied a 20% linear gradient. See before and after below for both a light image and a dark image.
> 

I only have experience with that technique on beamer sized screens. (Mostly with lyrics on live camera feeds) so I didn't have any addition to that option.

But the option with the darker background looks good 👍 Nice done.

**Pull request merged**
